# Generated by Django 2.2.1 on 2020-03-17 18:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+20[10-11-12-15]-xxxx-xxxx'", regex='^\\+201[0|1|2|5][0-9]{8}')])),
                ('profiles', models.ImageField(default='images/default_profile.png', upload_to='images/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('fb_profile', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
